import tkinter
from tkinter import *

top=Tk()
Lb=Listbox(top)
Lb.insert(1, 'python')
Lb.insert(2, 'java')
Lb.insert(3, 'c++')
Lb.insert(4, 'c#')
Lb.insert(5, 'javascript')
Lb.insert(6, 'php')
Lb.insert(7, 'html')
Lb.insert(8, 'ruby')
Lb.insert(9, 'swift')
Lb.insert(10, 'sql')
Lb.insert(11, 'perl')
Lb.insert(12, 'scala')
Lb.insert(13, 'rust')
Lb.insert(14, 'kotlin')
Lb.insert(15, 'matlab')
Lb.insert(16, 'forth')
Lb.pack()
top.mainloop()